# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce_4.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiny_field', tinymce_4.fields.TinyMCEModelField(blank=True, verbose_name='TinyMCEModelField')),
            ],
        ),
    ]
