# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce_4.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiny_field', tinymce_4.fields.TinyMCEModelField(blank=True, null=True, verbose_name=b'TinyMCEModelField')),
            ],
        ),
    ]
