# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-26 02:35
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create(
        is_active=True,
        is_staff=True,
        is_superuser=True,
        # Hash of 'admin' string
        password='pbkdf2_sha256$36000$pQxyKcmh0rHD$1nDFtLWhwVVxmx5+RuktHC3mOW8sAoF2Xt174FYHuVA=',  # noqa
        username='admin',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('tiny_example', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
